name: Minify and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  minify:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Fonts
            Themes

      - name: Install Minifier
        shell: "bash"
        working-directory: .
        run: |
          sudo apt-get update
          sudo apt-get install minify

      - name: Minify
        shell: "bash"
        working-directory: .
        run: minify -v -v --json-keep-numbers --json-precision 0 --recursive --sync --output dist/ Fonts Themes

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"

  deploy:
    needs: minify

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
